Loc["en"] = {
    error = {
        ["cancel"] = "Cancelled",
        ["seat_taken"] = "Someone is already sitting there..",
        ["not_clockin"] = "Not clocked in!",
        ["wrong_ingred"] = "You don't have the correct items",
        ["noshear"] = "You must have scissors for this!",
        ["inway"] = " in the way",
    },
    success = {
        ["washed_hands"] = "You've washed your hands!",
        ["retrieved"] = "Retrieved ",
        ["marked"] = "Job Vehicle Marked on Map",
    },
    mark = {
        ["veh_mark"] = "Job Vehicle",
    },
    target = {
        ["sit"] = "Sit Down",
        ["weed"] = "Prepared Items",
        ["table"] = "Open Table",
        ["store"] = "Store",
        ["hands"] = "Wash Your Hands",
        ["counter"] = "Open Counter",
        ["charge"] = "Charge Customer",
        ["bong"] = "Hit the Bong",
        ["trimming"] = "Trim Weed",
        ["joints"] = "Roll Joints",
        ["oven"] = "Use Oven",
        ["harvest"] = "Harvest",
        ["duty"] = "Toggle Duty",
        ["boss"] = "Open Bossmenu",
        ["dui_add"] = "Add Image",
        ["dui_reset"] = "Reset Image",
        ["dui_clear"] = "Clear Image",
        ["job_veh"] = "Job Vehicle",
    },
    menu = {
        ["close"] = "Close",
        ["header_joints"] = "🚬 Joints Menu 🚬",
        ["header_harvest"] = "🌿 Harvest Menu 🌿",
        ["header_oven"] = "🍳 Oven Menu 🍳",
        ["header_trimming"] = "✂️ Weed Trimming ✂️",
        ["header_bong"] = "Bong",
        ["header_tablebong"] = "Table Bong Menu",
        ["garage"] = "Job Garage",
        ["out_veh"] = "Vehicle out of Garage",
        ["remove_veh"] = "Remove Vehicle",
        ["plate"] = "<br> Plate: ",
        ["dui_new"] = "Enter New Image URL",
        ["dui_change"] = "Change",
        ["dui_url"] = "HTML Link",
    },
    progressbar = {
        ["progress_washing"] = "Washing hands",
        ["progress_eat"] = "Eating ",
        ["progress_smoke"] = "Smoking ",
        ["progress_rolling"] = "Rolling ",
        ["progress_cook"] = "Cooking ",
        ["progress_harvest"] = "Harvesting ",
        ["progress_trimming"] = "Trimming ",
    },
}