Loc["en"] = {
    error = {
        ["someone_sitting"] = "Someone is already sitting there..",
        ["not_cloked_in"] = "Not clocked in!",
        ["cancelled"] = "Cancelled",
        ["no_correct_ingredients"] = "You don't have the correct ingredients",
        ["in_way"] = " in the way",
    },
    success = {
        ["have_washed_hands"] = "You've washed your hands!",
        ["retrieved"] = "Retrieved ",
    },
    target = {
        ["open_shelves"] = "Open Shelves",
        ["open_locker"] = "Open Locker",
        ["open_fridge"] = "Open Fridge",
        ["open_storage"] = "Open Storage",
        ["open_bossmenu"] = "Open Bossmenu",
        ["open_cabinet"] = "Open Cabinet",
        ["open_table"] = "Open Table",
        ["open_tray"] = "Open Tray",
        ["grab_box"] = "Grab Empty Box",
        ["grill"] = "Use Burger Grill",
        ["deepfryer"] = "Use Deep Fryer",
        ["chopping_board"] = "Use Chopping Board",
        ["prepare_food"] = "Prepare Food",
        ["prepare_drinks"] = "Prepare Drinks",
        ["prepare_coffee"] = "Prepare Coffee",
        ["prepare_icecream"] = "Prepare IceCream",
        ["grab_toy"] = "Grab Toy",
        ["wash_hands"] = "Wash Your Hands",
        ["charge_customer"] = "Charge Customer",
        ["toggle_duty"] = "Toggle Duty",
        ["job_vehicles"] = "Job Vehicles",
        ["sit"] = "Sit Down",
        ["vehicle_map"] = "Job Vehicle Marked on Map",
        ["job_veh"] = "Job Vehicle",
    },
    progressbar = {
        ["washing_hands"] = "Washing hands",
        ["grab_box"] = "Grabbing Empty Box",
        ["pouring"] = "Pouring ",
        ["receiving"] = "Receiving ",
        ["slicing"] = "Slicing ",
        ["preparing"] = "Preparing ",
        ["cooking"] = "Cooking ",
        ["frying"] = "Frying ",
        ["eating"] = "Eating ",
        ["opening"] = "Opening ",
        ["drinking"] = "Drinking ",
        ["making"] = "Making ",
    },
    menu = {
        ["food_cabinet"] = "Food Cabinet",
        ["header_grill"] = "Grill",
        ["header_fryer"] = "Fryer",
        ["header_choppingboard"] = "Chopping Board",
        ["header_icecream"] = "Ice Cream Menu",
        ["header_donut"] = "Donut Menu",
        ["prepare_food"] = "Prepare Food",
        ["header_drinks"] = "Drinks Dispenser",
        ["header_coffee"] = "Coffee",
        ["job_garage"] = "Job Garage",
        ["out_of_garage"] = "Vehicle out of Garage",
        ["garage_vehicle"] = "Vehicle: ",
        ["vehicle_plate"] = "Plate",
        ["remove_vehicle"] = "Remove Vehicle",
        ["close"] = "Close",
    },
    dui = {
        ["add_image"] = "Add Image",
        ["reset_image"] = "Reset Image",
        ["clear_image"] = "Clear Image",
        ["new_url"] = "Enter New Image URL",
        ["change"] = "Change",
    },
    warning = {},
}